controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api:
    resource:
        path: ../src/Controller/
        namespace: App\Controller\Api
    type: annotation
    prefix: /api
    defaults:
        _format: json